"""create four joined tables with food_or_drink

Revision ID: 9e95ef3be945
Revises: a9409f931308
Create Date: 2021-02-04 17:46:40.179745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e95ef3be945'
down_revision = 'a9409f931308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    food_or_drink_customers_tables = op.create_table('food_or_drink_customers',
                                                     sa.Column(
                                                         'customer_id', sa.Integer(), nullable=True),
                                                     sa.Column(
                                                         'food_or_drink_id', sa.Integer(), nullable=True),
                                                     sa.ForeignKeyConstraint(
                                                         ['customer_id'], ['customers.id'], ),
                                                     sa.ForeignKeyConstraint(['food_or_drink_id'], [
                                                                             'food_or_drinks.id'], )
                                                     )
    ingredient_food_or_drinks_tables = op.create_table('ingredient_food_or_drinks',
                                                       sa.Column(
                                                           'ingredient_id', sa.Integer(), nullable=True),
                                                       sa.Column(
                                                           'food_or_drink_id', sa.Integer(), nullable=True),
                                                       sa.ForeignKeyConstraint(['food_or_drink_id'], [
                                                                               'food_or_drinks.id'], ),
                                                       sa.ForeignKeyConstraint(
                                                           ['ingredient_id'], ['ingredients.id'], )
                                                       )
    # menue_food_or_drinks_tables=op.create_table('menue_food_or_drinks',
    # sa.Column('menue_id', sa.Integer(), nullable=True),
    # sa.Column('food_or_drink_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['food_or_drink_id'], ['food_or_drinks.id'], ),
    # sa.ForeignKeyConstraint(['menue_id'], ['menues.id'], )
    # )
    table_food_or_drinks_tables = op.create_table('table_food_or_drinks',
                                                  sa.Column(
                                                      'food_or_drink_id', sa.Integer(), nullable=True),
                                                  sa.Column(
                                                      'table_id', sa.Integer(), nullable=True),
                                                  sa.ForeignKeyConstraint(['food_or_drink_id'], [
                                                                          'food_or_drinks.id'], ),
                                                  sa.ForeignKeyConstraint(
                                                      ['table_id'], ['tables.id'], )
                                                  )
    # ### end Alembic commands ###

    op.bulk_insert(food_or_drink_customers_tables, [
        {"customer_id": 1, "food_or_drink_id": 1},
        {"customer_id": 1, "food_or_drink_id": 2},
        {"customer_id": 2, "food_or_drink_id": 2},
        {"customer_id": 2, "food_or_drink_id": 4},
        {"customer_id": 2, "food_or_drink_id": 3},
        {"customer_id": 2, "food_or_drink_id": 1},
        {"customer_id": 3, "food_or_drink_id": 1},
        {"customer_id": 3, "food_or_drink_id": 4},
    ])
    op.bulk_insert(ingredient_food_or_drinks_tables, [
        {"food_or_drink_id": 1, "ingredient_id": 1},
        {"food_or_drink_id": 1, "ingredient_id": 2},
        {"food_or_drink_id": 1, "ingredient_id": 3},
        {"food_or_drink_id": 1, "ingredient_id": 4},
        {"food_or_drink_id": 1, "ingredient_id": 5},
        {"food_or_drink_id": 1, "ingredient_id": 6},
        {"food_or_drink_id": 3, "ingredient_id": 1},
        {"food_or_drink_id": 3, "ingredient_id": 5},
        {"food_or_drink_id": 3, "ingredient_id": 6},
        {"food_or_drink_id": 3, "ingredient_id": 8},
        {"food_or_drink_id": 2, "ingredient_id": 7},
        {"food_or_drink_id": 4, "ingredient_id": 9},
    ])
    # op.bulk_insert(menue_food_or_drinks_tables,[
    #     {"menue_id":1, "food_or_drink_id":1},
    #     {"menue_id":1, "food_or_drink_id":2},
    #     {"menue_id":1, "food_or_drink_id":3},
    #     {"menue_id":1, "food_or_drink_id":4},
    #     ])
    op.bulk_insert(table_food_or_drinks_tables, [
        {"food_or_drink_id": 1, "table_id": 1},
        {"food_or_drink_id": 2, "table_id": 1},
        {"food_or_drink_id": 2, "table_id": 2},
        {"food_or_drink_id": 1, "table_id": 2},
        {"food_or_drink_id": 3, "table_id": 2},
        {"food_or_drink_id": 1, "table_id": 2},
        {"food_or_drink_id": 1, "table_id": 3},
        {"food_or_drink_id": 4, "table_id": 3},
    ])


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('table_food_or_drinks')
    # op.drop_table('menue_food_or_drinks')
    # op.drop_table('ingredient_food_or_drinks')
    # op.drop_table('food_or_drink_customers')
    # ### end Alembic commands ###
