"""Create customer table

Revision ID: 4387a091c131
Revises: 2fab07cd5de9
Create Date: 2021-02-04 12:44:35.343186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4387a091c131'
down_revision = '2fab07cd5de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    customers_table = op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('tipp', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('server_review', sa.String(), nullable=True),
    sa.Column('server_rating', sa.Float(), nullable=True),
    sa.Column('order_issue', sa.String(), nullable=True),
    sa.Column('instagram', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(customers_table, [
        {"table_number":1, "tipp": 3.00, "total_price":None, "server_review":"She was very nice but spilled my husbands drink all over us. At least she got me a towel, and offered to clean it up.", "server_rating":3.50, "order_issue":"Didn't get my drink with my meal", "instagram": None},
        {"table_number":2, "tipp": 7.00, "total_price":None, "server_review":"Kind of looked like a famous dj I used to listen too, he even gave me extra bacon for free. What a man!", "server_rating":5.00,"order_issue":None, "instagram": None},
        {"table_number":3, "tipp": 1.00, "total_price":None, "server_review":"This guy was horrible, we asked about the special and he just started muttering about 'he who shall not be named'. It was annoying and very unprofessional", "server_rating":1.00, "order_issue":"Food was cold", "instagram": None},
    ])
    # customer1 = Customer(
    #     table_number = 1,
    #     tipp = 2.00,
    #     total_price = None,
    #     server_review = "She was very nice but spilled my husbands drink all over us. At least she got me a towel, and offered to clean it up.",
    #     server_rating = 3.5,
    #     order_issue = "Didn't get my beer",
    #     instagram = None
    # )
    # customer2 = Customer(
    #     table_number = 2,
    #     tipp = 2.00,
    #     total_price = None,
    #     server_review = "Kind of looked like a famous dj I used to listen too, he even gave me extra bacon for free. What a man!",
    #     server_rating = 5,
    #     order_issue = "Didn't get my beer",
    #     instagram = None
    # )
    # customer3 = Customer(
    #     table_number = 3,
    #     tipp = 2.00,
    #     total_price = None,
    #     server_review = "This guy was horrible, we asked about the special and he just started muttering about 'he who shall not be named'. It was annoying and very unprofessional",
    #     server_rating = 1,
    #     order_issue = None,
    #     instagram = None
    # )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
