"""empty message

Revision ID: e193c2bce1b8
Revises: 9e95ef3be945
Create Date: 2021-02-06 18:06:47.908190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e193c2bce1b8'
down_revision = '9e95ef3be945'
branch_labels = None
depends_on = None

# help
## Question should i delete this??
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menues', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'user_id')
    op.drop_column('menues', 'qr_code')
    # ### end Alembic commands ###
