"""Create Menue table

Revision ID: 6fbc9bdaa240
Revises: 82d2df03d7aa
Create Date: 2021-02-04 12:07:28.692783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbc9bdaa240'
down_revision = '82d2df03d7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menue_table = op.create_table('menues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('menue_name', sa.String(), nullable=True),
    sa.Column('food_item', sa.String(), nullable=True),
    sa.Column('menue_array', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(menue_table, [
        {"user_id": 1, "menue_name": "Example Menue", "food_item":"Entree", "menue_array":None, "picture":None, "qr_code": None },
    ])

# menue1 = Menue(
#         user_id = 1,
#         menue_name = 'Example Menue',
#         food_item = 'Pasta',
#         menue_array = None,
#         qr_code = None,
#         picture = None
#     )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menues')
    # ### end Alembic commands ###
