"""create employees table

Revision ID: 6883a964268d
Revises: 313bb71cd800
Create Date: 2021-02-04 11:07:17.781133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6883a964268d'
down_revision = '313bb71cd800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    employee_table = op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(employee_table,
    [
    {"user_id":1, "first_name": "Karen", "last_name":"Heffer", "salary":15.00, "table_number":1, "picture":None},
    {"user_id":1, "first_name": "Steve", "last_name":"Aioli", "salary":11.00, "table_number":2, "picture":None},
    {"user_id":1, "first_name": "Harry", "last_name":"Proper", "salary":8.00, "table_number":3, "picture":None}
    ])

    # employees1 = Employee(
    #     user_id = 1,
    #     first_name = "Karen",
    #     last_name = "Heffer",
    #     salary = 15.00,
    #     table_number = 1,
    #     picture = None
    # )

    # employees2 = Employee(
    #     user_id = 1,
    #     first_name = "Steve",
    #     last_name = "Aioli",
    #     salary = 11.00,
    #     table_number = 2,
    #     picture = None
    # )

    # employees3 = Employee(
    #     user_id = 1,
    #     first_name = "Harry",
    #     last_name = "Proper",
    #     salary = 8.00,
    #     table_number = 3,
    #     picture = None
    # )
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
