"""empty message

Revision ID: 52b96ecc5966
Revises: 9e95ef3be945
Create Date: 2021-02-22 17:44:47.228618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b96ecc5966'
down_revision = '9e95ef3be945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('menu_list', sa.String(), nullable=True),
    sa.Column('food_or_drink_list', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menue_food_or_drinks',
    sa.Column('menue_id', sa.Integer(), nullable=True),
    sa.Column('food_or_drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_or_drink_id'], ['food_or_drinks.id'], ),
    sa.ForeignKeyConstraint(['menue_id'], ['menues.id'], )
    )
    op.drop_column('tables', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('menue_food_or_drinks')
    op.drop_table('menu_lists')
    # ### end Alembic commands ###
